services:
  - type: web
    name: spaceship-impostor-api
    env: node
    buildCommand: npm run build:server
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: spaceship-impostor-api
          property: port
    healthCheckPath: /health

  - type: web
    name: spaceship-impostor-frontend
    env: static
    buildCommand: npm run build:client
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html